//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipsis.DAl.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderr
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MarketID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<double> M2 { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string CargoCode { get; set; }
        public Nullable<int> CargoID { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Markett Markett { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual User User { get; set; }
    }
}
